Class {
	#name : #ManifestProyectoHuertas,
	#superclass : #PackageManifest,
	#category : #'ProyectoHuertas-Manifest'
}

{ #category : #'code-critics' }
ManifestProyectoHuertas class >> ruleRBBadMessageRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#ProyectoHuertas)) #'2019-11-17T10:56:11.75683-03:00') )
]

{ #category : #'code-critics' }
ManifestProyectoHuertas class >> ruleRBMissingTranslationsInMenusRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#ProyectoHuertas)) #'2020-03-29T14:26:07.713208-03:00') )
]

{ #category : #'code-critics' }
ManifestProyectoHuertas class >> ruleRBStringConcatenationRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#ProyectoHuertas)) #'2019-11-14T22:26:18.924963-03:00') )
]
